import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { queryClient } from "@/lib/react-query";
import { QueryClientProvider } from "@tanstack/react-query";
import StandardErrorBoundary from "./errors/handleErrors";
import ErrorBoundary from "./errors/handleErrors";
import App from "./app";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <QueryClientProvider client={queryClient}>
        <body className={inter.className}>
          <StandardErrorBoundary><App/></StandardErrorBoundary>
        </body>
      </QueryClientProvider>
    </html>
  );
}
